services:
  - type: web
    name: restaurant-reservation-api
    env: node
    region: oregon
    plan: starter
    buildCommand: npm ci --include=dev && npm run build && npm run migration:run
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_SYNC
        value: false
      - key: DB_LOGGING
        value: false
      - key: PORT
        value: 3000
    healthCheckPath: /health
